version: "3"

services:
  
  jenkins-master:
    image: meetveracity/jenkins-master
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      - ADMIN_PASSWORD=admin
      - GITHUB_ORGANIZATION=meetveracity

  
  